name: implicitly_animated_reorderable_list_fork
description: Implicitly animated reorderable list fork
version: 1.0.1
homepage: https://github.com/skazkiful/implicitly_animated_reorderable_list_fork

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.8.1
  flutter:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
